### ISSUE TITLE
New version of this mod keep creating missing texture,  and T-posed ragdoll 

### ISSUE THREAD

**Issue by lakilolom** [Ramalayha/gibsplat2#11]
![20210615135219_1](https://user-images.githubusercontent.com/85920465/121995478-f1067500-cde1-11eb-8cec-c6021901e7fe.jpg)
![20210615135206_1](https://user-images.githubusercontent.com/85920465/121995487-f499fc00-cde1-11eb-850b-0b233533e2cb.jpg)
![20210615135045_1](https://user-images.githubusercontent.com/85920465/121995506-fb287380-cde1-11eb-8eee-1efb53f2c52b.jpg)

After mods got update, those bones keep showing up T-posed ragdolls on the top somehow.

and blood trails making missing textures on the wall.

i usually combined this mod with Borrowed blood mod and Custom blood particles, but i never seeing this kind of bugs.

how can i fix this?

**Comment by Ramalayha** [comment]
These should both be fixed now.
