### ISSUE TITLE
This addon for some reason prevents conveyor belts in maps like gm_waste_repurposing from moving objects placed on them

### ISSUE THREAD

**Issue by MemeticGitHubUser** [Ramalayha/gibsplat2#7]
Without GibSplat2 installed
https://user-images.githubusercontent.com/40185397/116604999-dc871f80-a8fc-11eb-8055-3d3ed2f6b4a3.mp4
With Gibsplat2 installed
https://user-images.githubusercontent.com/40185397/116605126-04768300-a8fd-11eb-81a2-84ca4c7be6e0.mp4

**Comment by Ramalayha** [comment]
This should be fixed now

**Comment by MemeticGitHubUser** [comment]
Okay!
